// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {structures} from '../models';

export function CheckInternetConnection():Promise<boolean>;

export function CheckOpenDb():Promise<boolean>;

export function CheckXTimeInternetConnection(arg1:number):Promise<boolean>;

export function Cleanup():Promise<void>;

export function GetAgenda(arg1:any,arg2:any):Promise<Array<structures.LocalAgenda>>;

export function GetGrades(arg1:string):Promise<string>;

export function GetPageContent(arg1:string):Promise<string>;

export function GetParentDir():Promise<string>;

export function GetProfile():Promise<string>;

export function GetUserData():Promise<structures.UserSettings>;

export function GetYears():Promise<string>;

export function GlobalRefresh(arg1:string,arg2:string,arg3:string):Promise<string>;

export function InitDiscordRPC():Promise<void>;

export function RefreshAgenda(arg1:any,arg2:any):Promise<Array<structures.LocalAgenda>>;

export function RefreshGrades(arg1:string):Promise<Array<structures.Grades>>;

export function RefreshProfile():Promise<string>;

export function UpdateDiscordRPC(arg1:string,arg2:string):Promise<void>;

export function UpdateUserEula():Promise<boolean>;

export function UpdateUserTheme(arg1:string):Promise<boolean>;

export function VerifyUser(arg1:string,arg2:string):Promise<string>;

export function WriteLogFile(arg1:string,arg2:string):Promise<void>;
