// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckOpenDb() {
  return window['go']['backend']['App']['CheckOpenDb']();
}

export function Cleanup() {
  return window['go']['backend']['App']['Cleanup']();
}

export function GetPageContent(arg1) {
  return window['go']['backend']['App']['GetPageContent'](arg1);
}

export function GetParentDir() {
  return window['go']['backend']['App']['GetParentDir']();
}

export function GetUserData() {
  return window['go']['backend']['App']['GetUserData']();
}

export function InitDiscordRPC() {
  return window['go']['backend']['App']['InitDiscordRPC']();
}

export function UpdateDiscordRPC(arg1, arg2) {
  return window['go']['backend']['App']['UpdateDiscordRPC'](arg1, arg2);
}

export function UpdateUserEula() {
  return window['go']['backend']['App']['UpdateUserEula']();
}

export function UpdateUserTheme(arg1) {
  return window['go']['backend']['App']['UpdateUserTheme'](arg1);
}

export function WriteLogFile(arg1, arg2) {
  return window['go']['backend']['App']['WriteLogFile'](arg1, arg2);
}
