// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckInternetConnection() {
  return window['go']['backend']['App']['CheckInternetConnection']();
}

export function CheckOpenDb() {
  return window['go']['backend']['App']['CheckOpenDb']();
}

export function CheckXTimeInternetConnection(arg1) {
  return window['go']['backend']['App']['CheckXTimeInternetConnection'](arg1);
}

export function Cleanup() {
  return window['go']['backend']['App']['Cleanup']();
}

export function GetAgenda(arg1, arg2) {
  return window['go']['backend']['App']['GetAgenda'](arg1, arg2);
}

export function GetGrades(arg1) {
  return window['go']['backend']['App']['GetGrades'](arg1);
}

export function GetPageContent(arg1) {
  return window['go']['backend']['App']['GetPageContent'](arg1);
}

export function GetParentDir() {
  return window['go']['backend']['App']['GetParentDir']();
}

export function GetProfile() {
  return window['go']['backend']['App']['GetProfile']();
}

export function GetUserData() {
  return window['go']['backend']['App']['GetUserData']();
}

export function GetYears() {
  return window['go']['backend']['App']['GetYears']();
}

export function GlobalRefresh(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GlobalRefresh'](arg1, arg2, arg3);
}

export function InitDiscordRPC() {
  return window['go']['backend']['App']['InitDiscordRPC']();
}

export function RefreshAgenda(arg1, arg2) {
  return window['go']['backend']['App']['RefreshAgenda'](arg1, arg2);
}

export function RefreshGrades(arg1) {
  return window['go']['backend']['App']['RefreshGrades'](arg1);
}

export function RefreshProfile() {
  return window['go']['backend']['App']['RefreshProfile']();
}

export function UpdateDiscordRPC(arg1, arg2) {
  return window['go']['backend']['App']['UpdateDiscordRPC'](arg1, arg2);
}

export function UpdateUserEula() {
  return window['go']['backend']['App']['UpdateUserEula']();
}

export function UpdateUserTheme(arg1) {
  return window['go']['backend']['App']['UpdateUserTheme'](arg1);
}

export function VerifyUser(arg1, arg2) {
  return window['go']['backend']['App']['VerifyUser'](arg1, arg2);
}

export function WriteLogFile(arg1, arg2) {
  return window['go']['backend']['App']['WriteLogFile'](arg1, arg2);
}
