// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {structures} from '../models';

export function CheckOpenDb():Promise<boolean>;

export function Cleanup():Promise<void>;

export function GetPageContent(arg1:string):Promise<string>;

export function GetParentDir():Promise<string>;

export function GetUserData():Promise<structures.UserSettings>;

export function InitDiscordRPC():Promise<void>;

export function UpdateDiscordRPC(arg1:string,arg2:string):Promise<void>;

export function UpdateUserEula():Promise<boolean>;

export function UpdateUserTheme(arg1:string):Promise<boolean>;

export function WriteLogFile(arg1:string,arg2:string):Promise<void>;
