// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckInternetConnection() {
  return window['go']['backend']['App']['CheckInternetConnection']();
}

export function CheckOpenDb() {
  return window['go']['backend']['App']['CheckOpenDb']();
}

export function CheckXTimeInternetConnection(arg1) {
  return window['go']['backend']['App']['CheckXTimeInternetConnection'](arg1);
}

export function ConnectUser(arg1, arg2) {
  return window['go']['backend']['App']['ConnectUser'](arg1, arg2);
}

export function DeconnectUser() {
  return window['go']['backend']['App']['DeconnectUser']();
}

export function DeleteEvent(arg1) {
  return window['go']['backend']['App']['DeleteEvent'](arg1);
}

export function DeleteOldData() {
  return window['go']['backend']['App']['DeleteOldData']();
}

export function GetAbsences() {
  return window['go']['backend']['App']['GetAbsences']();
}

export function GetAgenda(arg1, arg2) {
  return window['go']['backend']['App']['GetAgenda'](arg1, arg2);
}

export function GetAllEvents() {
  return window['go']['backend']['App']['GetAllEvents']();
}

export function GetCourses() {
  return window['go']['backend']['App']['GetCourses']();
}

export function GetEvents() {
  return window['go']['backend']['App']['GetEvents']();
}

export function GetEventsLike(arg1) {
  return window['go']['backend']['App']['GetEventsLike'](arg1);
}

export function GetGrades() {
  return window['go']['backend']['App']['GetGrades']();
}

export function GetParentDir() {
  return window['go']['backend']['App']['GetParentDir']();
}

export function GetProfile() {
  return window['go']['backend']['App']['GetProfile']();
}

export function GetProjectById(arg1) {
  return window['go']['backend']['App']['GetProjectById'](arg1);
}

export function GetProjects() {
  return window['go']['backend']['App']['GetProjects']();
}

export function GetRegisteredUsers() {
  return window['go']['backend']['App']['GetRegisteredUsers']();
}

export function GetStartStatus() {
  return window['go']['backend']['App']['GetStartStatus']();
}

export function GetStartupStatus() {
  return window['go']['backend']['App']['GetStartupStatus']();
}

export function GetUserData() {
  return window['go']['backend']['App']['GetUserData']();
}

export function GetYears() {
  return window['go']['backend']['App']['GetYears']();
}

export function InitDiscordRPC() {
  return window['go']['backend']['App']['InitDiscordRPC']();
}

export function JoinProjectGroup(arg1, arg2, arg3) {
  return window['go']['backend']['App']['JoinProjectGroup'](arg1, arg2, arg3);
}

export function QuitProjectGroup(arg1, arg2, arg3) {
  return window['go']['backend']['App']['QuitProjectGroup'](arg1, arg2, arg3);
}

export function RefreshAbsences() {
  return window['go']['backend']['App']['RefreshAbsences']();
}

export function RefreshAgenda(arg1, arg2) {
  return window['go']['backend']['App']['RefreshAgenda'](arg1, arg2);
}

export function RefreshGrades() {
  return window['go']['backend']['App']['RefreshGrades']();
}

export function ReturnRefreshAbsencesState() {
  return window['go']['backend']['App']['ReturnRefreshAbsencesState']();
}

export function ReturnRefreshGradesState() {
  return window['go']['backend']['App']['ReturnRefreshGradesState']();
}

export function ReturnRefreshScheduleState() {
  return window['go']['backend']['App']['ReturnRefreshScheduleState']();
}

export function SaveEvents(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['SaveEvents'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateDiscordRPC(arg1, arg2) {
  return window['go']['backend']['App']['UpdateDiscordRPC'](arg1, arg2);
}

export function UpdateUserEula() {
  return window['go']['backend']['App']['UpdateUserEula']();
}

export function UpdateUserPassword(arg1, arg2) {
  return window['go']['backend']['App']['UpdateUserPassword'](arg1, arg2);
}

export function UpdateUserTheme(arg1) {
  return window['go']['backend']['App']['UpdateUserTheme'](arg1);
}

export function VerifyUser(arg1, arg2) {
  return window['go']['backend']['App']['VerifyUser'](arg1, arg2);
}

export function WriteLogFile(arg1, arg2) {
  return window['go']['backend']['App']['WriteLogFile'](arg1, arg2);
}
