// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {structures} from '../models';
import {backend} from '../models';

export function CheckInternetConnection():Promise<boolean>;

export function CheckOpenDb():Promise<boolean>;

export function CheckXTimeInternetConnection(arg1:number):Promise<boolean>;

export function ConnectUser(arg1:string,arg2:string):Promise<structures.UserSettings>;

export function DeconnectUser():Promise<void>;

export function DeleteEvent(arg1:number):Promise<boolean>;

export function DeleteOldData():Promise<boolean>;

export function GetAbsences():Promise<Array<structures.LocalAbsences>>;

export function GetAgenda(arg1:any,arg2:any):Promise<Array<structures.LocalAgenda>>;

export function GetAllEvents():Promise<Array<structures.Event>>;

export function GetCourses():Promise<string>;

export function GetEvents():Promise<Array<structures.Event>>;

export function GetEventsLike(arg1:string):Promise<Array<structures.Event>>;

export function GetGrades():Promise<Array<structures.LocalGrades>>;

export function GetParentDir():Promise<string>;

export function GetProfile():Promise<string>;

export function GetProjectById(arg1:number):Promise<string>;

export function GetProjects():Promise<string>;

export function GetRegisteredUsers():Promise<Array<structures.UserSettings>>;

export function GetStartStatus():Promise<backend.StartupStatus>;

export function GetStartupStatus():Promise<backend.StartupStatus>;

export function GetUserData():Promise<structures.UserSettings>;

export function GetYears():Promise<string>;

export function InitDiscordRPC():Promise<void>;

export function JoinProjectGroup(arg1:number,arg2:number,arg3:number):Promise<boolean>;

export function QuitProjectGroup(arg1:number,arg2:number,arg3:number):Promise<boolean>;

export function RefreshAbsences():Promise<Array<structures.LocalAbsences>>;

export function RefreshAgenda(arg1:any,arg2:any):Promise<Array<structures.LocalAgenda>>;

export function RefreshGrades():Promise<Array<structures.LocalGrades>>;

export function ReturnRefreshAbsencesState():Promise<boolean>;

export function ReturnRefreshGradesState():Promise<boolean>;

export function ReturnRefreshScheduleState():Promise<boolean>;

export function SaveEvents(arg1:string,arg2:any,arg3:string,arg4:string,arg5:string):Promise<void>;

export function UpdateDiscordRPC(arg1:string,arg2:string):Promise<void>;

export function UpdateUserEula():Promise<boolean>;

export function UpdateUserPassword(arg1:string,arg2:string):Promise<boolean>;

export function UpdateUserTheme(arg1:string):Promise<boolean>;

export function VerifyUser(arg1:string,arg2:string):Promise<string>;

export function WriteLogFile(arg1:string,arg2:string):Promise<void>;
