// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function CheckOpenDb():Promise<boolean>;

export function Cleanup():Promise<void>;

export function GetPageContent(arg1:string):Promise<string>;

export function GetUserData():Promise<db.UserSettings>;
