// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckOpenDb() {
  return window['go']['main']['App']['CheckOpenDb']();
}

export function Cleanup() {
  return window['go']['main']['App']['Cleanup']();
}

export function GetPageContent(arg1) {
  return window['go']['main']['App']['GetPageContent'](arg1);
}

export function GetUserData() {
  return window['go']['main']['App']['GetUserData']();
}
